### ISSUE TITLE
No shared schemes for version 0.2.2

### ISSUE THREAD

**Issue by pikor** [podkovyrin/Keyboardy#10]
Hi,

building version 0.2.0 with Carthage works fine.
Building version 0.2.2 with Carthage results in error `Dependency "xxx" has no shared framework schemes`.
I think selecting target as `Shared` will fix the problem.

**Comment by podkovyrin** [comment]
Fixed. Please try `0.2.3`

**Comment by pikor** [comment]
Yep, `0.2.3` is working great, thanks!
