### ISSUE TITLE
Swift3

### ISSUE THREAD

**Issue by kronik** [podkovyrin/Keyboardy#4]
Any plans to switch to Swift3?

**Comment by podkovyrin** [comment]
Needs some time to push updated podspec.

**Comment by podkovyrin** [comment]
Can't push due to https://github.com/CocoaPods/CocoaPods/issues/5864. Will wait until Cocoapods 1.1.0 will be released

**Comment by danipralea** [comment]
It was fixed apparently.
I still have issues with it though.

**Comment by podkovyrin** [comment]
pod was pushed to trunk. Swift 3 version - `0.2.0`
